### PR TITLE
Update poolRegistry.tsx

### PR DESCRIPTION
**Pull request by sirejanke**
add cloudstake

### CODE REVIEW

**Comment by KarishmaBothara** [comment]
Hi @sirejanke 
To prove ownership of these accounts can you pls send this transaction from the controller or stash.

5H6rggyghnocQJbKEG9KhqDkYMQmzmHAaZJfu1rdVa49rktw": "Cloudstake"



Thanks

**Comment by sirejanke** [comment]
WhatsApp Image 2022-02-01 at 12 15 57
 hi sending the transaction is not possible, only with only 5H6rggyghnocQJbKEG9KhqDkYMQmzmHAaZJfu1rdVa49rktw

**Comment by KarishmaBothara** [comment]
Hi @sirejanke 

Can you please try using the controller account - 5CArdAQQHXGiVy1UE59Ddozgbee6wtxeatdaGoyzZiNZ4WzT
The remark needs to be Cloudstake.

0x436c6f75647374616b65  is the string 'Cloudstake' hexified

console.log(util.stringToHex("Cloudstake"));
> 0x436c6f75647374616b65

**Comment by sirejanke** [comment]
https://uncoverexplorer.com/extrinsic/11325283-1 @KarishmaBothara

**Review by KarishmaBothara — APPROVED** [review]

**Pull request merged**
