### PR TITLE
Update poolRegistry.tsx

### PR DESCRIPTION
**Pull request by tayrosa**

### CODE REVIEW

**Comment by holygits** [comment]
Hi @tayrosa , thanks for the PR.

From this this account `5EZzxmJY5dyexnKsv8Q9xQY34Ugc56hjwM1CYCX8Nsinye2J` or its controller account, can you send the following system.remark transaction to show proof of ownership

Screen Shot 2021-04-22 at 9 03 48


`0x4d4f4f4e` is the string 'MOON' hex encoded
```js
console.log(util.stringToHex('MOON'));
> 0x4d4f4f4e
```

Reply here with the block hash which has the transaction then happy to approve the PR!

**Comment by tayrosa** [comment]
Hi @holygits

OK, Executed！

**Comment by holygits** [comment]
https://uncoverexplorer.com/extrinsic/6417826-1
Screen Shot 2021-04-22 at 15 23 30

controller:
Screen Shot 2021-04-22 at 15 28 03

**Review by holygits — APPROVED** [review]

**Comment by holygits** [comment]
Pool name will appear after the next UI deployment

**Pull request merged**
