### PR TITLE
make send asset a modal

### PR DESCRIPTION
**Pull request by matjazc**

### CODE REVIEW

**Comment by KarishmaBothara** [comment]
Have tested it functionally on my local.. works well.. Can we remove the 'Send assets' from the left panel.. as per design now that will part of accounts page..

**Comment by alexsednz** [comment]
The code looks good to me as a non React/js expert. The PR can be improved by:

- Assigning it to the reviewers
- Adding a brief description explaining the approach
- Creating an issue on github (equivalent to our internal Jira task): Example issue #31
- In the PR description mentioning if the above issue is fully addressed or not. Example: closes #31 

Also, the branch that you worked on could be better named something like `feature/31-modal-send-asset`. The first part "feature" specifies this is a new feature. If you were fixing an issue it could start with fix/ and so on. 31 is an example of an issue number that could be used in the branch name. 
Having said this, you may notice we haven't fully followed the above-mentioned standard in our previous PRs and branch names. At the moment we take the above practice as an improvement guideline and we'd try to get better at it.

**Comment by matjazc** [comment]
> Have tested it functionally on my local.. works well.. Can we remove the 'Send assets' from the left panel.. as per design now that will part of accounts page..

Sure, I will remove side bar item

**Comment by matjazc** [comment]
> The code looks good to me as a non React/js expert. The PR can be improved by:
> 
> * Assigning it to the reviewers
> * Adding a brief description explaining the approach
> * Creating an issue on github (equivalent to our internal Jira task): Example issue #31
> * In the PR description mentioning if the above issue is fully addressed or not. Example: closes #31
> 
> Also, the branch that you worked on could be better named something like `feature/31-modal-send-asset`. The first part "feature" specifies this is a new feature. If you were fixing an issue it could start with fix/ and so on. 31 is an example of an issue number that could be used in the branch name.
> Having said this, you may notice we haven't fully followed the above-mentioned standard in our previous PRs and branch names. At the moment we take the above practice as an improvement guideline and we'd try to get better at it.

This is a nice set of good practices, I agree with all points. Thanks for raising this.

**Comment by holygits** [comment]
is there a way to close modal?

**Comment by matjazc** [comment]
new PR created

**Pull request closed without merging**
