### PR TITLE
Update poolRegistry.tsx

### PR DESCRIPTION
**Pull request by katatou827**

### CODE REVIEW

**Comment by KarishmaBothara** [comment]
hi @katatou827 ,

can you please send a system remark transaction from this account or it's controller as proof of ownership:
see this comment to get the idea: #113 (comment)
then happy to approve

**Comment by KarishmaBothara** [comment]
Hi @katatou827,

System remark tx sent from this account's controller account is a different string. Can you please use  https://codebeautify.org/string-hex-converter and then use the hex value generated and send system remark tx.
Also it will be nice if you can send the link of your tx on uncover for us to verify.

**Comment by katatou827** [comment]
image

**Comment by KarishmaBothara** [comment]
looks good... can you please rebase and resolve the conflicts.. I can approve and merge it then...

**Comment by katatou827** [comment]
> 
> 
> looks good... can you please rebase and resolve the conflicts.. I can approve and merge it then...

hi @KarishmaBothara 

Please tell me the specific operation.

**Pull request merged**
