### PR TITLE
Update poolRegistry.tsx

### PR DESCRIPTION
**Pull request by mikuasakai**

### CODE REVIEW

**Comment by mikuasakai** [comment]
Sincerely yours

**Comment by KarishmaBothara** [comment]
Hi @mikuasakai,

Can you please send a system remark transaction from this account or it's controller as proof of ownership:
see this comment to get the idea: #113 (comment)
then happy to approve

**Comment by mikuasakai** [comment]
Hi!, @KarishmaBothara 

system.remark OK.

**Comment by KarishmaBothara** [comment]
> Hi!, @KarishmaBothara
> 
> system.remark OK.

Thanks... Can you please share the screenshot or link for (system.remark OK.) 
Once I get that, I can approve this..

**Review by sirejanke — CHANGES_REQUESTED** [review]
"5DLV7RVNDE7pEuZ1i6pa3kFnpiR1S8dtnRfYN24h3BkhSt9R": "Binnostake",

**Comment by KarishmaBothara** [comment]
> "5DLV7RVNDE7pEuZ1i6pa3kFnpiR1S8dtnRfYN24h3BkhSt9R": "Binnostake",

@sirejanke - can you please create a new PR...with similar changes for your pool..

**Review by holygits — APPROVED** [review]

**Pull request merged**
