### PR TITLE
Update poolRegistry.tsx

### PR DESCRIPTION
**Pull request by katatou827**

### CODE REVIEW

**Comment by holygits** [comment]
hi @katatou827, to prove ownership of these accounts can you pls send this transaction from the controller or stash.

```
5G23iUgMscn2afQeLeG9Ta4Jub6vSqGzRniFY8PJ4nsV6wao": "Gyan",
"5ENsn4mnjsUkwujJwPaBUe37vTcW5sVkqSixEBCWgE6ZiYNp": "SHINWA"
```
Screen Shot 2021-11-09 at 12 40 51

**Comment by katatou827** [comment]
Please proceed with the procedure.

**Comment by katatou827** [comment]
https://uncoverexplorer.com/extrinsic/9859293-1
https://uncoverexplorer.com/extrinsic/9859275-1

**Comment by katatou827** [comment]
hi holygits,I sent system.remark.

**Review by KarishmaBothara — APPROVED** [review]

**Pull request merged**
