### PR TITLE
Update poolRegistry.tsx

### PR DESCRIPTION
**Pull request by imai740**

### CODE REVIEW

**Comment by holygits** [comment]
hi @imai740,

can you please send a `system` `remark` transaction from this account or it's controller as proof of ownership:
see this comment to get the idea: https://github.com/cennznet/ui/pull/113#issuecomment-824356949
then happy to approve

**Comment by imai740** [comment]
hi holygits,
OK!

**Comment by katatou827** [comment]
hi holygits,

I sended the system.remark transaction,
Then what should I do?

**Comment by imai740** [comment]
hi holygits,

I sended the system.remark transaction,
Then what should I do?

**Review by holygits — APPROVED** [review]
transaction link: https://uncoverexplorer.com/extrinsic/6889593-1

**Comment by imai740** [comment]
hi holygits,
It doesn't look like "HODL" yet...

https://cennznet.io/#/staking

**Pull request merged**
