### PR TITLE
Update poolRegistry.tsx

### PR DESCRIPTION
**Pull request by katatou827**

### CODE REVIEW

**Comment by katatou827** [comment]
Please approve.

**Comment by holygits** [comment]
hi @katatou827 
can you follow this process to prove ownership of the controller/stash
https://github.com/cennznet/ui/pull/113#issuecomment-824356949

**Comment by katatou827** [comment]
I tried it !

**Review by holygits — APPROVED** [review]

**Comment by holygits** [comment]
https://uncoverexplorer.com/extrinsic/7244502-1

**Pull request merged**
